# Generated by Django 3.2.10 on 2023-12-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iac_django_app', '0004_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=255)),
                ('lesson_content', models.TextField()),
                ('lesson_file_type', models.CharField(max_length=10)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iac_django_app.module')),
            ],
        ),
    ]
