# Generated by Django 3.2.10 on 2023-12-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iac_django_app', '0006_alter_lesson_lesson_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='file_type',
            new_name='lesson_file_type',
        ),
    ]
