# Generated by Django 4.2.7 on 2023-12-01 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "course_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("course_name", models.CharField(max_length=100)),
                ("course_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "studentid",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                ("module_id", models.AutoField(primary_key=True, serialize=False)),
                ("week", models.PositiveIntegerField()),
                ("module_description", models.TextField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iac_django_app.courses",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Files",
            fields=[
                ("file_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=10)),
                (
                    "file",
                    models.FileField(
                        storage="django.core.files.storage.FileSystemStorage",
                        upload_to="files/",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iac_django_app.module",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iac_django_app.courses",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iac_django_app.student",
                    ),
                ),
            ],
        ),
    ]
