# Generated by Django 4.2.7 on 2023-12-01 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iac_django_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Courses",
            new_name="Course",
        ),
        migrations.RenameModel(
            old_name="Files",
            new_name="File",
        ),
    ]
