# Generated by Django 4.2.7 on 2023-12-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "iac_django_app",
            "0002_alter_student_options_remove_student_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
