# Generated by Django 4.2.7 on 2023-11-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashesi',
            name='email',
            field=models.EmailField(default=None, max_length=100, unique=True),
        ),
    ]
